config/routes.rb
Friendphotos::Application.routes.draw do
  root :to => 'static#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  get '/sign_in' => 'sessions#new', :as => 'sign_in'
  get '/sign_out' => 'sessions#destroy', :as => 'sign_out'


  # Routes for the Friend resource:
  # CREATE
  # get '/friends/new', controller: 'friends', action: 'new', as: 'new_friend'
  # post '/friends', controller: 'friends', action: 'create'

  # READ
  get '/friends', controller: 'friends', action: 'index', as: 'friends'
  # get '/friends/:id', controller: 'friends', action: 'show', as: 'friend'

  # UPDATE
  # get '/friends/:id/edit', controller: 'friends', action: 'edit', as: 'edit_friend'
  # put '/friends/:id', controller: 'friends', action: 'update'

  # DELETE
  # delete '/friends/:id', controller: 'friends', action: 'destroy'
  #------------------------------

  # Routes for the Photo resource:
  # CREATE
  # get '/photos/new', controller: 'photos', action: 'new', as: 'new_photo'
  # post '/photos', controller: 'photos', action: 'create'

  # READ
  get '/photos', controller: 'photos', action: 'index', as: 'photos'
  # get '/photos/:id', controller: 'photos', action: 'show', as: 'photo'

  # UPDATE
  # get '/photos/:id/edit', controller: 'photos', action: 'edit', as: 'edit_photo'
  # put '/photos/:id', controller: 'photos', action: 'update'

  # DELETE
  # delete '/photos/:id', controller: 'photos', action: 'destroy'
  #------------------------------

  # Routes for the User resource:
  # CREATE
  # get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  # post '/users', controller: 'users', action: 'create'

  # READ
  # get '/users', controller: 'users', action: 'index', as: 'users'
  # get '/users/:id', controller: 'users', action: 'show', as: 'user'

  # UPDATE
  # get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  # put '/users/:id', controller: 'users', action: 'update'

  # DELETE
  # delete '/users/:id', controller: 'users', action: 'destroy'
  #------------------------------
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user

  def Friend.query_friends(user)

  uid = user.uid
  access_token = user.access_token

  query1request = "SELECT name, uid FROM user WHERE uid IN (SELECT uid1 FROM friend WHERE uid2=#{uid})"

  options = { :access_token => "#{access_token}" }
    friends_api = Fql.execute({
    :query1 => query1request
    }, options)

  friends_clean_api = friends_api[0]["fql_result_set"]

    @friends = []

    friends_clean_api.each do |friend|
      f = Friend.new
      f.name = friend["name"]
      f.uid = friend["uid"]
      @friends << f
    end

    return @friends.sort_by!(&:name)
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  def Photo.query_photos(friend_id, user)

  uid = user.uid
  access_token = user.access_token
  recipient_id = friend_id
  query1request = "SELECT src_big, caption, object_id, owner, aid, created FROM photo WHERE object_id IN(SELECT object_id FROM photo_tag WHERE subject = #{uid}) AND object_id IN(SELECT object_id FROM photo_tag WHERE subject=#{recipient_id})"

  options = { :access_token => "#{access_token}" }
    photos_api = Fql.execute({
    :query1 => query1request
    }, options)

  photos_clean_api = photos_api[0]["fql_result_set"]

    @photos = []

    photos_clean_api.each do |photo|
      s = Photo.new
      s.source_url = photo["src_big"]
      s.fb_object_id = photo["object_id"]
      s.user_id = photo["owner"]
      @photos << s
    end

    return @photos
  end
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :photos
has_many :friends

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.access_token = auth.credentials.token
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.name = auth.info.name
      user.email = auth.info.email
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index
    @friends = Friend.all
    @fb_friends = Friend.query_friends(User.find(session[:user_id]))
  end

  def show
    @friend = Friend.find_by_id(params[:id])
  end

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.new
    @friend.name = params[:name]
    @friend.uid = params[:uid]

    if @friend.save
            redirect_to friends_url
          else
      render 'new'
    end
  end

  def edit
    @friend = Friend.find_by_id(params[:id])
  end

  def update
    @friend = Friend.find_by_id(params[:id])
    @friend.name = params[:name]
    @friend.uid = params[:uid]

    if @friend.save
            redirect_to friends_url
          else
      render 'edit'
    end
  end

  def destroy
    @friend = Friend.find_by_id(params[:id])
    @friend.destroy
        redirect_to friends_url
      end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
    @fb_friends = Friend.query_friends(User.find(session[:user_id]))
    @chosen_uid = params[:uid]
    @fb_photos = Photo.query_photos(params[:uid], User.find(session[:user_id]))
  end

  def show
    @photo = Photo.find_by_id(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new
    @photo.user_id = params[:user_id]
    @photo.source_url = params[:source_url]
    @photo.t.integer = params[:t.integer]

    if @photo.save
            redirect_to photos_url
          else
      render 'new'
    end
  end

  def edit
    @photo = Photo.find_by_id(params[:id])
  end

  def update
    @photo = Photo.find_by_id(params[:id])
    @photo.user_id = params[:user_id]
    @photo.source_url = params[:source_url]
    @photo.t.integer = params[:t.integer]

    if @photo.save
            redirect_to photos_url
          else
      render 'edit'
    end
  end

  def destroy
    @photo = Photo.find_by_id(params[:id])
    @photo.destroy
        redirect_to photos_url
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
  user = User.from_omniauth(env["omniauth.auth"])
  session[:user_id] = user.id
  redirect_to friends_url, :notice => "You successfully logged in, #{current_user.first_name}!"
end

def destroy
  session[:user_id] = nil
  redirect_to root_path, :notice => "You have been successfully logged out."
end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.access_token = params[:access_token]
    @user.uid = params[:uid]
    @user.provider = params[:provider]
    
    if @user.save
            redirect_to users_url
          else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.name = params[:name]
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.access_token = params[:access_token]
    @user.uid = params[:uid]
    @user.provider = params[:provider]
    
    if @user.save
            redirect_to users_url
          else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
        redirect_to users_url
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/edit.html.erb
<h1>Editing Friend #<%= @friend.id %></h1>


<%= form_tag(friend_url(@friend), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @friend.name %>
  </div>

  <div>
    <%= label_tag :uid %><br />
    <%= number_field_tag :uid, @friend.uid %>
  </div>

  
  <div>
    <%= submit_tag "Update Friend" %>
  </div>

<% end %>

app/views/friends/index.html.erb
<br />
<br />

<div class="row">
  <%= form_tag(photos_url, method: 'get', :class => 'form-horizontal span6 offset2') do %>

    <div class="control-group">
      <%= label_tag :uid, "Select a Friend:", :class => "control-label" %>
        <div class="controls">
          <%= select_tag :uid, options_from_collection_for_select(@fb_friends, :uid, :name, @chosen_uid) %>
        <div>
    </div>
    </div>
    </div>

    <div>
      <button type="submit" class="btn btn-success span3 offset1">See Friendship Photos</button>
    </div>
  <% end %>
</div>

app/views/friends/new.html.erb
<h1>New Friend</h1>


<%= form_tag(friends_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

    <div>
    <%= label_tag :uid %><br />
    <%= number_field_tag :uid %>
  </div>

  
  <div>
    <%= submit_tag "Create Friend" %>
  </div>
<% end %>

app/views/friends/show.html.erb
<h1>Friend #<%= @friend.id %></h1>

<p>
  <b>Name:</b>
  <%= @friend.name %>
</p>

<p>
  <b>Uid:</b>
  <%= @friend.uid %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendphotos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="/">FriendPhotos</a>
      <% if current_user %>
        <a href="<%= sign_out_url %>"><button class="btn btn-primary">Sign Out</button></a>
      <% else %>
        <a href="/auth/facebook"><button class="btn btn-primary">Sign in Via Facebook</button></a>
      <% end %>
    </div>
  </div>

<div class="container">
   <% if notice.present? %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
   <% end %>



<%= yield %>

</div>
</body>
</html>

app/views/photos/edit.html.erb
<h1>Editing Photo #<%= @photo.id %></h1>


<%= form_tag(photo_url(@photo), method: 'put') do %>

  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id, @photo.user_id %>
  </div>

  <div>
    <%= label_tag :source_url %><br />
    <%= text_field_tag :source_url, @photo.source_url %>
  </div>

  <div>
    <%= label_tag :t.integer %><br />
    <%= text_field_tag :t.integer, @photo.t.integer %>
  </div>

  
  <div>
    <%= submit_tag "Update Photo" %>
  </div>

<% end %>

app/views/photos/index.html.erb
<div class="row">
  <%= form_tag(photos_url, method: 'get', :class => 'form-horizontal span6 offset2') do %>

    <div class="control-group">
      <%= label_tag :uid, "Select a Friend:", :class => "control-label" %>
        <div class="controls">
          <%= select_tag :uid, options_from_collection_for_select(@fb_friends, :uid, :name, @chosen_uid) %>
        <div>
    </div>
    </div>
    </div>

    <div>
      <button type="submit" class="btn btn-success span3 offset1">See Friendship Photos</button>
    </div>
  <% end %>
</div>

<br />

<div class="row clearfix">
  <ul class="thumbnails">
    <% @fb_photos.each do |photo| %>
    <li class="span4">
    <a href="#" class="thumbnail">
      <img data-src="holder.js/300x200">
        <div class="new_photo" style="background-image: url(<%= photo.source_url %>); background-size: 290px auto">
        </div>
    </a>
    </li>
    <% end %>
  </ul>
</div>

app/views/photos/new.html.erb
<h1>New Photo</h1>


<%= form_tag(photos_url, method: 'post') do %>


  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id %>
  </div>

    <div>
    <%= label_tag :source_url %><br />
    <%= text_field_tag :source_url %>
  </div>

    <div>
    <%= label_tag :t.integer %><br />
    <%= text_field_tag :t.integer %>
  </div>

  
  <div>
    <%= submit_tag "Create Photo" %>
  </div>
<% end %>

app/views/photos/show.html.erb
<h1>Photo #<%= @photo.id %></h1>

<p>
  <b>User:</b>
  <%= @photo.user_id %>
</p>

<p>
  <b>Source url:</b>
  <%= @photo.source_url %>
</p>

<p>
  <b>T.integer:</b>
  <%= @photo.t.integer %>
</p>

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @user.name %>
  </div>

  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name, @user.first_name %>
  </div>

  <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name, @user.last_name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :access_token %><br />
    <%= text_field_tag :access_token, @user.access_token %>
  </div>

  <div>
    <%= label_tag :uid %><br />
    <%= number_field_tag :uid, @user.uid %>
  </div>

  <div>
    <%= label_tag :provider %><br />
    <%= text_field_tag :provider, @user.provider %>
  </div>

  
  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Access token</th>
      <th>Uid</th>
      <th>Provider</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.access_token %></td>
      <td><%= user.uid %></td>
      <td><%= user.provider %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

    <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name %>
  </div>

    <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name %>
  </div>

    <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

    <div>
    <%= label_tag :access_token %><br />
    <%= text_field_tag :access_token %>
  </div>

    <div>
    <%= label_tag :uid %><br />
    <%= number_field_tag :uid %>
  </div>

    <div>
    <%= label_tag :provider %><br />
    <%= text_field_tag :provider %>
  </div>

  
  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Access token:</b>
  <%= @user.access_token %>
</p>

<p>
  <b>Uid:</b>
  <%= @user.uid %>
</p>

<p>
  <b>Provider:</b>
  <%= @user.provider %>
</p>